export const SET_CURRENT_USER = 'SET_CURRENT_USER',
  TOGGLE_CART_VISIBILITY = 'TOGGLE_CART_VISIBILITY',
  ADD_ITEM = 'ADD_ITEM',
  CLEAR_ITEM_FROM_CART = 'CLEAR_ITEM_FROM_CART',
  REMOVE_ITEM = 'REMOVE_ITEM',
  FETCH_COLLECTIONS_START = 'FETCH_COLLECTIONS_START',
  FETCH_COLLECTIONS_SUCCESS = 'FETCH_COLLECTIONS_SUCCESS',
  FETCH_COLLECTIONS_FAILURE = 'FETCH_COLLECTIONSFAILURE';
